# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  # Box settings

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "client1"

  config.vm.hostname = "client1"

  config.vm.box_check_update = false

  # Network settings

  config.vm.network "private_network", type: "dhcp"

  config.vm.network "private_network", ip: "172.16.24.2"

  # Folder settings

  # Provider settings
  
  config.vm.provider "virtualbox" do |vb|
    
    vb.name = "Client_1"
    vb.memory = "1024"
  
  end
  
  # Provision settings

  #config.vm.provision "shell", inline: <<-SHELL

  #   apt-get update
  #   apt-get install -y apache2
  
  #SHELL

end
