# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  # Box settings

  config.vm.box = "debian/bullseye64"

  config.vm.define "server1"

  config.vm.hostname = "server1"

  config.vm.box_check_update = false

  # Network settings

  config.vm.network "public_network", ip: "10.100.0.5", bridge: "wlo1"

  config.vm.network "private_network", ip: "10.93.24.2"
      
  config.vm.network "private_network", ip: "10.11.93.2"

  # Folder settings

  # Provider settings
  
  config.vm.provider "virtualbox" do |vb|
    
    vb.name = "Server_1"
    vb.memory = "2048"
  
  end
  
  # Provision settings

  #config.vm.provision "shell", inline: <<-SHELL

  #   apt-get update
  #   apt-get install -y apache2
  
  #SHELL

end
