trigger: 
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: List all Folders in Build.ArtifactStagingDirectory
  inputs:
    targetType: 'inline'
    script: |
      tree $(Build.ArtifactStagingDirectory)

- task: Bash@3
  displayName: List all Folders in Build.BinariesDirectory
  inputs:
    targetType: 'inline'
    script: |
      tree $(Build.BinariesDirectory)
      
- task: Bash@3
  displayName: List all Folders in System.DefaultWorkingDirectory
  inputs:
    targetType: 'inline'
    script: |
      tree $(System.DefaultWorkingDirectory)

- task: Bash@3
  displayName: List all Folders in Pipeline.WorkSpace
  inputs:
    targetType: 'inline'
    script: |
      tree $(Pipeline.WorkSpace)